version: '3.11'

services:
  backend:
    container_name: api
    build:
      context: backend
      dockerfile: docker/Dockerfile
    ports:
      - "8081:80"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
