version: "3.11"
services:
  postgres:
    container_name: postgres-dev
    hostname: db_postgres
    image: postgres:14.6
    restart: on-failure
    expose:
      - "5432"
    ports:
      - "5432:5432"
      - "5433:5432"
    env_file:
      - ./backend/env/.env.postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    container_name: fastapi-dev
    build:
      context: backend
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "8083:80"
    env_file:
      - ./backend/env/.env.fastapi
    volumes:
      - ./backend/src:/app/src
    restart: on-failure


volumes:
  postgres-data:
    driver: local
