version: '3.11'

services:
  backend:
    container_name: api
    build:
      context: backend
      dockerfile: docker/Dockerfile
    ports:
      - "8081:80"
    env_file:
      - backend/.env
    depends_on:
      - postgres
      - pgadmin
      - redis
#      - minio
#      - cache_storage
#      - geocodes_api
    links:
      - postgres
      - redis
    volumes:
      - ./backend:/app


