version: '3.11'

services:
  backend:
    container_name: api
    build:
      context: backend
      dockerfile: docker/Dockerfile
    ports:
      - "8081:80"
    env_file:
      - .envs/backend/.env
#    environment:
#      - POSTGRES_HOST=${POSTGRES_HOST}
#      - POSTGRES_PORT=${POSTGRES_PORT}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#      - SECRET_KEY=${SECRET_KEY}
#      - ALGORITHM=${ALGORITHM}
#      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}