version: '3.11'

services:
  backend:
    container_name: api
    build:
      context: backend
      dockerfile: docker/Dockerfile
    ports:
      - "8081:80"
    environment:
      - POSTGRES_HOST=51.83.130.148
      - POSTGRES_PORT=5001
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=wHhdUAMX79gExGsZv2NYyJ
      - POSTGRES_DB=tripplaner
