import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    padding: 20,
  },
  input: {
    height: 40,
    marginBottom: 10,
    borderWidth: 1,
    padding: 10,
    borderRadius: 15,
  },
  inputTitle: {
    fontWeight: 'bold',
    fontSize: 18,
    color: '#000',
  },
  multiline: {
    height: 120,
    textAlignVertical: 'top',
    marginBottom: 10,
    borderWidth: 1,
    padding: 10,
    borderRadius: 15,
  },
  slider: {
    width: '100%',
    height: 40,
    marginBottom: 10,
  },
  imageContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    padding: 10,
    marginTop: 10,
    backgroundColor: '#f0f0f0',
    borderRadius: 10,
  },
  thumbnail: {
    width: 200,
    height: 150,
    marginRight: 10,
    borderRadius: 5,
  },
  closeButton: {
    position: 'absolute',
    top: 20,
    right: 20,
  },
  closeText: {
    color: '#FFF',
    fontSize: 18,
  },
  imageModal: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  modalImage: {
    width: '80%',
    height: '80%',
    resizeMode: 'contain',
  },
  removeButton: {
    borderRadius: 20,
    borderColor: 'rgba(189,190,190,0.60)',
    borderWidth: 5,
    width: 40,
    height: 40,
    backgroundColor: 'rgba(189,190,190,0.75)',
    position: 'absolute',
    top: 20,
    right: 20,
    marginRight: 5,
    shadowColor: 'black',
    shadowOpacity: 0.3,
    shadowRadius: 5,
    shadowOffset: {
      width: 0,
      height: 2,
    },
  },
  removeButtonText: {
    padding: 1,
    marginTop: -8,
    color: '#ef3c3c',
    textAlign: 'center',
    fontSize: 28,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  buttonPhoto: {
    backgroundColor: '#20B2AA',
    borderRadius: 20,
    padding: 10,
    elevation: 2,
    marginTop: 10,
    width: '30%',
    alignSelf: 'flex-start',
  },
  buttonSubmit: {
    backgroundColor: '#20B2AA',
    borderRadius: 20,
    padding: 10,
    elevation: 2,
    marginTop: 10,
    width: '50%',
    alignSelf: 'flex-end',
    position: 'absolute',
    marginBottom: 10,
    right: 10,
    bottom: 10,
  },
  buttonText: {
    color: 'white',
    fontSize: 14,
    textAlign: 'center',
  },
  sliderTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'black',
  },
});
