version: "3.11"
services:
  postgres:
    container_name: tripplaner
    image: postgres:14.6
    hostname: postgres
    ports:
      - "5432:5432"
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tripplaner
      POSTGRES_DB: tripplaner
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: tripplaner@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: on-failure

volumes:
  postgres-data:
