import { Attraction, Opinion } from "../../types";

export const attractionsExamples: Attraction[] = [
  {
    id: 1,
    name: 'Royal Castle',
    user_id: 1,
    country: 'Poland',
    city: 'Warsaw',
    region: 'Masovian',
    category: 'Historical',
    description: 'Beautiful castle in the heart of Warsaw.',
    rating: 4,
    latitude: 52.2474,
    longitude: 21.0147,
    open_hours: { open: 9, close: 18 },
    address: 'Castle Square',
    time_spent: 2,
    price: 20,
    visits: 500,
  },
  {
    id: 2,
    name: 'Wawel Castle',
    user_id: 2,
    country: 'Poland',
    city: 'Krakow',
    region: 'Lesser Poland',
    category: 'Historical',
    description: 'Historic castle in Krakow.',
    rating: 4,
    latitude: 50.0547,
    longitude: 19.9354,
    open_hours: { open: 10, close: 17 },
    address: 'Wawel 5',
    time_spent: 3,
    price: 25,
    visits: 700,
  },
  {
    id: 3,
    name: 'Malbork Castle',
    user_id: 3,
    country: 'Poland',
    city: 'Malbork',
    region: 'Pomeranian',
    category: 'Historical',
    description: 'World\'s largest brick castle.',
    rating: 5,
    latitude: 54.0389,
    longitude: 19.0284,
    open_hours: { open: 10, close: 16 },
    address: 'Stare Miasto 1',
    time_spent: 4,
    price: 30,
    visits: 1000,
  },
  {
    id: 4,
    name: 'Berlin Wall',
    user_id: 1,
    country: 'Germany',
    city: 'Berlin',
    region: 'Brandenburg',
    category: 'Historical',
    description: 'Remnant of the Cold War.',
    rating: 3,
    latitude: 52.5074,
    longitude: 13.4395,
    open_hours: { open: 8, close: 20 },
    address: 'Bernauer Strasse 111',
    time_spent: 2,
    price: 15,
    visits: 400,
  },
  {
    id: 5,
    name: 'Neuschwanstein Castle',
    user_id: 2,
    country: 'Germany',
    city: 'Füssen',
    region: 'Bavaria',
    category: 'Historical',
    description: 'Fairytale castle in the Bavarian Alps.',
    rating: 5,
    latitude: 47.5576,
    longitude: 10.7498,
    open_hours: { open: 9, close: 18 },
    address: 'Neuschwansteinstrasse 20',
    time_spent: 5,
    price: 35,
    visits: 1200,
  },
  {
    id: 6,
    name: 'Cologne Cathedral',
    user_id: 3,
    country: 'Germany',
    city: 'Cologne',
    region: 'North Rhine-Westphalia',
    category: 'Religious',
    description: 'Gothic cathedral and UNESCO World Heritage Site.',
    rating: 4,
    latitude: 50.9375,
    longitude: 6.9603,
    open_hours: { open: 8, close: 18 },
    address: 'Domkloster 4',
    time_spent: 2,
    price: 10,
    visits: 800,
  },
  {
    id: 7,
    name: 'Eiffel Tower',
    user_id: 1,
    country: 'France',
    city: 'Paris',
    region: 'Île-de-France',
    category: 'Landmark',
    description: 'Iconic symbol of Paris.',
    rating: 5,
    latitude: 48.8584,
    longitude: 2.2944,
    open_hours: { open: 9, close: 23 },
    address: 'Champ de Mars, 5 Avenue Anatole France',
    time_spent: 3,
    price: 20,
    visits: 1500,
  },
  {
    id: 8,
    name: 'Louvre Museum',
    user_id: 2,
    country: 'France',
    city: 'Paris',
    region: 'Île-de-France',
    category: 'Museum',
    description: 'World\'s largest art museum and a historic monument.',
    rating: 4,
    latitude: 48.8610,
    longitude: 2.3350,
    open_hours: { open: 9, close: 18 },
    address: 'Rue de Rivoli',
    time_spent: 4,
    price: 15,
    visits: 2000,
  },
  {
    id: 9,
    name: 'Mont Saint-Michel',
    user_id: 3,
    country: 'France',
    city: 'Le Mont-Saint-Michel',
    region: 'Normandy',
    category: 'Historical',
    description: 'Island commune with a medieval abbey.',
    rating: 4,
    latitude: 48.6367,
    longitude: -1.5115,
    open_hours: { open: 9, close: 19 },
    address: '50170 Mont-Saint-Michel',
    time_spent: 6,
    price: 25,
    visits: 800,
  },
];

export const reviewsExamples: Opinion[] = [
  {
    id: 1,
    author: 1,
    description: 'Great place! I enjoyed my time there.',
    images: [],
    rating: 4,
    title: 'Awesome Experience',
    price: 3,
    time_spent: 2,
  },
  {
    id: 2,
    author: 2,
    description: 'Beautiful attraction. Highly recommended.',
    images: [],
    rating: 5,
    title: 'A Must-Visit',
    price: 4,
    time_spent: 3,
  },
  {
    id: 3,
    author: 3,
    description: 'Not bad, but a bit overpriced.',
    images: [],
    rating: 3,
    title: 'Average Experience',
    price: 2,
    time_spent: 1,
  },
  {
    id: 4,
    author: 4,
    description: 'Terrible. I regret going there.',
    images: [],
    rating: 1,
    title: 'Waste of Time and Money',
    price: 1,
    time_spent: 1,
  },
  {
    id: 5,
    author: 5,
    description: 'Decent attraction. Could be better.',
    images: [],
    rating: 2,
    title: 'Not Impressed',
    price: 3,
    time_spent: 2,
  },
  {
    id: 6,
    author: 1,
    description: 'Great place! I enjoyed my time there.',
    images: ['https://bi.im-g.pl/im/43/6c/1b/z28756547AMP,Jezioro-Czyste.jpg',
      'https://bydgoszczinformuje.pl/wp-content/uploads/2023/10/Dab-Napoleona.jpg',
      'https://domyinterstyl.pl/wp-content/uploads/2023/09/Projekt-bez-nazwy-13.jpg'
    ],
    rating: 4,
    title: 'Awesome Experience',
    price: 3,
    time_spent: 2,
  },
  {
    id: 7,
    author: 2,
    description: 'Beautiful attraction. Highly recommended.',
    images: [],
    rating: 5,
    title: 'A Must-Visit',
    price: 4,
    time_spent: 3,
  },
  {
    id: 8,
    author: 3,
    description: 'Not bad, but a bit overpriced.',
    images: [],
    rating: 3,
    title: 'Average Experience',
    price: 2,
    time_spent: 1,
  },
  {
    id: 9,
    author: 4,
    description: 'Terrible. I regret going there.',
    images: [],
    rating: 1,
    title: 'Waste of Time and Money',
    price: 1,
    time_spent: 1,
  },
  {
    id: 10,
    author: 5,
    description: 'Decent attraction. Could be better.',
    images: [],
    rating: 2,
    title: 'Not Impressed',
    price: 3,
    time_spent: 2,
  },
  {
    id: 11,
    author: 1,
    description: 'Great place! I enjoyed my time there.',
    images: [],
    rating: 4,
    title: 'Awesome Experience',
    price: 3,
    time_spent: 2,
  },
  {
    id: 12,
    author: 2,
    description: 'Beautiful attraction. Highly recommended.',
    images: [],
    rating: 5,
    title: 'A Must-Visit',
    price: 4,
    time_spent: 3,
  },
  {
    id: 13,
    author: 3,
    description: 'Not bad, but a bit overpriced.',
    images: [],
    rating: 3,
    title: 'Average Experience',
    price: 2,
    time_spent: 1,
  },
  {
    id: 14,
    author: 4,
    description: 'Terrible. I regret going there.',
    images: [],
    rating: 1,
    title: 'Waste of Time and Money',
    price: 1,
    time_spent: 1,
  },
  {
    id: 15,
    author: 5,
    description: 'Decent attraction. Could be better.',
    images: [],
    rating: 2,
    title: 'Not Impressed',
    price: 3,
    time_spent: 2,
  },
];
