name: Python App Quality

on:
    pull_request:
      branches: 
        - dev
        - main


jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements/dev.txt"
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/dev.txt
      - name: Lint with ruff
        run: |
          python -m ruff check --verbose --format=github .
      - name: Lint with mypy
        run: |
          python -m mypy --show-error-codes --pretty --show-column-numbers --show-error-context .
    