name: Deploy to VPS and Build

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install -y curl jq sshpass openssh-client

      - name: Rebuild and rerun REST api
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OVH_SSH_HOST }}
          username: ${{ secrets.OVH_SSH_USERNAME }}
          password: ${{ secrets.OVH_SSH_PASSWORD }}
          script: |
            set -e # Stop the script on the first error

            # Define the repository directory
            REPO_DIR=trip-planer

            # Check if the repository directory exists
            if [ -d "$REPO_DIR" ]; then
              echo "Repository exists. Pulling latest changes."
              cd $REPO_DIR
              git pull origin dev || {
                echo "Failed to pull latest changes. Exiting."
                exit 1
              }
            else
              echo "Cloning repository."
              git clone -b dev https://${{ secrets.ACCESS_TOKEN_GIT }}@github.com/kwiats/trip-planer.git || {
                echo "Failed to clone repository. Exiting."
                exit 1
              }
            fi

            # Build the Docker image
            cd trip-planer/backend
            docker build -f docker/Dockerfile . -t api:latest || {
              echo "Docker build failed. Exiting."
              exit 1
            }

            # Stop and remove any existing container named 'api'
            docker stop api || true
            docker rm api || true

            # Run the new Docker container
            docker run --name api -d -p 8080:80 api:latest
