name: Python App Quality

on:
    pull_request:
      branches:  
        - dev
        - main

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "backend/requirements.txt"
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt
